use sobrinho;

CREATE TABLE IF NOT EXISTS membros (
    id INT NOT NULL AUTO_INCREMENT,
    usuario VARCHAR(16) NOT NULL UNIQUE,
    senha VARCHAR(12) NOT NULL,
    nome VARCHAR(30) NOT NULL,
    email VARCHAR(45) NOT NULL,
    PRIMARY KEY (id)
)  DEFAULT CHARSET=UTF8;
